# Generated by Django 3.1.4 on 2021-01-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('altmobile', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('full_face', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('proof_of_residence', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
