# Generated by Django 3.1.4 on 2021-01-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Users',
        ),
    ]
