# Generated by Django 3.1.4 on 2021-02-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_referrals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('card_id', models.CharField(max_length=255, unique=True)),
                ('card_pin', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
