# Generated by Django 3.1.4 on 2021-02-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='is_verified',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
