# Generated by Django 3.1.4 on 2021-02-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='unique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
