# Generated by Django 3.1.4 on 2021-01-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
