# Generated by Django 3.1.4 on 2021-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proofs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pop', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='wallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('sent', models.FloatField(blank=True, null=True)),
                ('received', models.FloatField(blank=True, null=True)),
                ('commission', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
