# Generated by Django 3.1.4 on 2021-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
