# Generated by Django 3.1.4 on 2021-01-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallets_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('sent', models.FloatField(blank=True, null=True)),
                ('received', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
