# Generated by Django 3.1.4 on 2021-01-14 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_accountnums'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnums',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
