# Generated by Django 3.1.4 on 2021-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='siteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('altphone', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('symbol', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('maintenance', models.CharField(blank=True, default=None, max_length=54, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('signup_msg', models.CharField(blank=True, max_length=500, null=True)),
                ('login_auth_msg', models.CharField(blank=True, max_length=500, null=True)),
                ('password_reset_msg', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
